### ISSUE TITLE
Watershed Distance Transform for 2D Data not working

### ISSUE THREAD

**Issue by riederd** [vanvalenlab/deepcell-tf#120]
Hi,

I'm tryining to run deepcell-tf using the "Watershed Distance Transform for 2D Data" notebook as python script on some of our images. For now I'm only using 2 sets of nuclear stain images each set has 1 image. However, unfortunately it seems not to work as expected.

After training the foreground/background separation model it crashes at step [5] and produces the following traceback:

Traceback (most recent call last):
  File "runDeepCellWatershedSeq.py", line 158, in <module>
    shear=False)
  File "/home/foo/miniconda3/envs/deepCell-tf/lib/python3.6/site-packages/DeepCell-0.1-py3.6.egg/deepcell/training.py", line 169, in train_model_sample
  File "/home/foo/miniconda3/envs/deepCell-tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1761, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/foo/miniconda3/envs/deepCell-tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 190, in fit_generator
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "/home/foo/miniconda3/envs/deepCell-tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1537, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/foo/miniconda3/envs/deepCell-tf/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2897, in __call__
    fetched = self._callable_fn(*array_vals)
  File "/home/foo/miniconda3/envs/deepCell-tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1454, in __call__
    self._session._session, self._handle, args, status, None)
  File "/home/foo/miniconda3/envs/deepCell-tf/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [10,2] vs. [10,4]
         [[Node: loss_1/softmax_1_loss/mul_1 = Mul[T=DT_FLOAT, _class=["loc:@training_1/SGD/gradients/loss_1/softmax_1_loss/mul_1_grad/Reshape_1"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_softmax_1_target_0_1/_1259, loss_1/softmax_1_loss/Log)]]
         [[Node: training_1/SGD/gradients/batch_normalization_15/cond/FusedBatchNorm_1_grad/FusedBatchNormGrad/_1481 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1300_...chNormGrad", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()

The problem seems to be: Incompatible shapes: [10,2] vs. [10,4]

How can this be fixed?

**Comment by willgraf** [comment]
It would be helpful if you could you post the code you're running to get this error.  I think I've run into this error before, but seeing the exact code would really help diagnose.

**Comment by riederd** [comment]
Sure,

I attached a zipped python script.
Thanks for looking at this.

[DeepCellWatershedSeq.zip](https://github.com/vanvalenlab/deepcell-tf/files/2647973/DeepCellWatershedSeq.zip)
