### ISSUE TITLE
discriminative_instance_loss_3D: tensordot: Matrix size-incompatible when using channels_first

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/deepcell-tf#19]
This is the stack trace seen when running bn_dense_feature_net_3D model and image_data_format = channels_first.  So far, this does not appear when using channels_last, but this may be because we error out beforehand.

Root cause comes from the loss function: discriminative_instance_loss_3D
```bash
Traceback (most recent call last):
  File "deepcell_scripts/mousebrain_train.py", line 94, in <module>
    train_model_on_training_data()
  File "deepcell_scripts/mousebrain_train.py", line 89, in train_model_on_training_data
    shear=False
  File "/usr/local/lib/python3.5/dist-packages/deepcell/dc_training_functions.py", line 399, in train_model_movie
    LearningRateScheduler(lr_sched)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 1598, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/training_generator.py", line 191, in fit_generator
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 1390, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2824, in __call__
    fetches=fetches, feed_dict=feed_dict, **self.session_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Matrix size-incompatible: In[0]: [256,2560], In[1]: [7680,256]
	 [[Node: loss/softmax_1_loss/Tensordot/MatMul = MatMul[T=DT_FLOAT, _class=["loc:@training/SGD/gradients/loss/softmax_1_loss/Tensordot/MatMul_grad/MatMul_1"], transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](loss/softmax_1_loss/Tensordot/Reshape, loss/softmax_1_loss/Tensordot/Reshape_1)]]
	 [[Node: loss/add_8/_279 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3384_loss/add_8", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'loss/softmax_1_loss/Tensordot/MatMul', defined at:
  File "deepcell_scripts/mousebrain_train.py", line 94, in <module>
    train_model_on_training_data()
  File "deepcell_scripts/mousebrain_train.py", line 89, in train_model_on_training_data
    shear=False
  File "/usr/local/lib/python3.5/dist-packages/deepcell/dc_training_functions.py", line 368, in train_model_movie
    model.compile(loss=loss_function, optimizer=optimizer)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 428, in compile
    output_loss = weighted_loss(y_true, y_pred, sample_weight, mask)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/training_utils.py", line 438, in weighted
    score_array = fn(y_true, y_pred)
  File "/usr/local/lib/python3.5/dist-packages/deepcell/dc_training_functions.py", line 366, in loss_function
    return discriminative_instance_loss_3D(y_true, y_pred)
  File "/usr/local/lib/python3.5/dist-packages/deepcell/dc_helper_functions.py", line 355, in discriminative_instance_loss_3D
    cells_summed = tf.tensordot(y_true, y_pred, axes=[[0, 1, 2, 3], [0, 1, 2, 3]])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 3004, in tensordot
    ab_matmul = matmul(a_reshape, b_reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 2122, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 4279, in mat_mul
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Matrix size-incompatible: In[0]: [256,2560], In[1]: [7680,256]
	 [[Node: loss/softmax_1_loss/Tensordot/MatMul = MatMul[T=DT_FLOAT, _class=["loc:@training/SGD/gradients/loss/softmax_1_loss/Tensordot/MatMul_grad/MatMul_1"], transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](loss/softmax_1_loss/Tensordot/Reshape, loss/softmax_1_loss/Tensordot/Reshape_1)]]
	 [[Node: loss/add_8/_279 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3384_loss/add_8", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by willgraf** [comment]
discriminative instance loss 3d has been replaced by a dimension tolerant loss function.  This issue is no longer relevant.
