### ISSUE TITLE
PiPy Installation

### ISSUE THREAD

**Issue by jesusdpa1** [vanvalenlab/deepcell-tf#329]
Good afternoon, 

Is there a way to install deepcell through pipy instead of the docker container?

**Comment by willgraf** [comment]
This is currently not supported, but a good idea!

**Comment by jesusdpa1** [comment]
I try compiling the project in my computer, and when trying to use the nuclear segmentation started getting the following error 

model = NuclearSegmentationModel(input_shape=(1,7056,9408), backbone='resnet50', use_pretrained_weights=True)
2020-03-31 15:34:50.570419: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-31 15:34:50.606398: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-31 15:34:50.606703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 with Max-Q Design computeCapability: 7.5
coreClock: 1.185GHz coreCount: 36 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 357.69GiB/s
2020-03-31 15:34:50.606863: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-03-31 15:34:50.606924: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory
2020-03-31 15:34:50.606982: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2020-03-31 15:34:50.607039: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2020-03-31 15:34:50.607093: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory
2020-03-31 15:34:50.607148: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory
2020-03-31 15:34:50.607202: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory
2020-03-31 15:34:50.607209: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1592] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-03-31 15:34:50.607581: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-31 15:34:50.634129: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2599990000 Hz
2020-03-31 15:34:50.634833: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f23fd5d9e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-31 15:34:50.634856: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-31 15:34:50.711836: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-31 15:34:50.712407: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f23fd3de60 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-03-31 15:34:50.712424: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2070 with Max-Q Design, Compute Capability 7.5
2020-03-31 15:34:50.712701: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-31 15:34:50.712710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      
Traceback (most recent call last):
  File "/home/jesusdpa/anaconda3/envs/imgpyjdpa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-e98b111e817d>", line 1, in <module>
    model = NuclearSegmentationModel(input_shape=(1,7056,9408), backbone='resnet50', use_pretrained_weights=True)
  File "/home/jesusdpa/PycharmProjects/codex_uf/deepcell/applications/nuclear_segmentation.py", line 71, in NuclearSegmentationModel
    norm_method='whole_image')
  File "/home/jesusdpa/PycharmProjects/codex_uf/deepcell/model_zoo/maskrcnn.py", line 456, in RetinaMask
    fixed_inputs = TensorProduct(required_channels)(norm)
  File "/home/jesusdpa/anaconda3/envs/imgpyjdpa/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 748, in __call__
    self._maybe_build(inputs)
  File "/home/jesusdpa/anaconda3/envs/imgpyjdpa/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2116, in _maybe_build
    self.build(input_shapes)
  File "/home/jesusdpa/PycharmProjects/codex_uf/deepcell/layers/tensor_product.py", line 129, in build
    if input_shape[channel_axis].value is None:
AttributeError: 'int' object has no attribute 'value'
