### ISSUE TITLE
Error received from peer ipv4:10.107.254.162:8500","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Servable not found for request: Specific(PhaseCytoSegmentation, 1)","grpc_status":5}"

### ISSUE THREAD

**Issue by PPPparry** [vanvalenlab/deepcell-tf#494]
**Describe the bug**
I found an issue "Job Failed: Traceback (most recent call last):
File "/usr/src/app/redis_consumer/consumers/base_consumer.py", line 201, in consume
status = self._consume(redis_hash)
File "/usr/src/app/redis_consumer/consumers/segmentation_consumer.py", line 130, in _consume
image = self.validate_model_input(image, model_name, model_version)
File "/usr/src/app/redis_consumer/consumers/base_consumer.py", line 255, in validate_model_input
model_metadata = self.get_model_metadata(model_name, model_version)
File "/usr/src/app/redis_consumer/consumers/base_consumer.py", line 349, in get_model_metadata
model_metadata = client.get_model_metadata()
File "/usr/src/app/redis_consumer/grpc_clients.py", line 274, in get_model_metadata
response = self._retry_grpc(request, request_timeout)
File "/usr/src/app/redis_consumer/grpc_clients.py", line 240, in _retry_grpc
raise err
File "/usr/src/app/redis_consumer/grpc_clients.py", line 207, in _retry_grpc
response = api_call(request, timeout=request_timeout)
File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 923, in __call__
return _end_unary_response_blocking(state, call, False, None)
File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.NOT_FOUND
details = "Servable not found for request: Specific(PhaseCytoSegmentation, 1)"
debug_error_string = "{"created":"@1614047448.191105631","description":"Error received from peer ipv4:10.107.254.162:8500","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Servable not found for request: Specific(PhaseCytoSegmentation, 1)","grpc_status":5}"
>"

when I predict an image with size 141*626

**To Reproduce**
The image is in attachments
![Cell_line2_ROI1](https://user-images.githubusercontent.com/26714289/108796308-66480300-75c3-11eb-9287-c2080e36e25b.png)

**Expected behavior**
I expect that deepcell can predict the segmentation mask on this image, thanks 

**Screenshots**

![image](https://user-images.githubusercontent.com/26714289/108796175-1b2df000-75c3-11eb-9e3e-911e5eb8d958.png)

**Comment by willgraf** [comment]
Thanks for the report.

[deepcell.org](https://deepcell.org/predict) has been updated to reflect the proper model versions.

**Comment by willgraf** [comment]
There seems to be an issue with the image you attached. Could you please either re-upload the image so I can make sure it works or let me know if [deepcell.org](https://deepcell.org/predict) works for you?

**Comment by willgraf** [comment]
I'm going to close this issue. Please re-open it if you are still experiencing issues.
