### ISSUE TITLE
Encounter "ValueError: 'a' cannot be empty unless no samples are taken"

### ISSUE THREAD

**Issue by jizhouh** [vanvalenlab/deepcell-tf#534]
Hello,
I encountered this error two days ago when I changed my data set. I could not figure it out by myself.
These are the stats of the data set that I am using now:

**Dataset Statistics: 
Image data shape:  (4, 10, 607, 607, 1)
Number of lineages (should equal batch size):  4
Total number of unique tracks (cells)      -  104
Total number of divisions                  -  12
Average cell density (cells/100 sq pixels) -  0.005916694033638306
Average number of frames per track         -  8**

I tried to increased or decreased the size of data set by manually rotating, mirroring, or simply copying & pasting the same data set, but the error did not disappear.

I also tried to change the value of **batch size**.  I found the fact that if **I set the batch size to 1**, then no matter what I done above (augmenting the data set), the program could only perform the first three iterations in the first epoch, and then threw the value error.

Epoch 1/10
  3/190 [..............................] - ETA: 1:43 - loss: 0.1958 - accuracy: 0.3889   

In contrast, if **I set batch size to larger value**, like 2, or 20 (still smaller than the number of lineages), then the program did not even perform those three iterations, and directly threw the value error.

Thanks a lot.

The following text is the detail of the error.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-41-10872695b363> in <module>
     30     validation_data=test_data,
     31     validation_steps=total_test_pairs // batch_size,
---> 32     callbacks=train_callbacks)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1859         use_multiprocessing=use_multiprocessing,
   1860         shuffle=shuffle,
-> 1861         initial_epoch=initial_epoch)
   1862 
   1863   def evaluate_generator(self,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1062           use_multiprocessing=use_multiprocessing,
   1063           model=self,
-> 1064           steps_per_execution=self._steps_per_execution)
   1065 
   1066       # Container that configures and calls `tf.keras.Callback`s.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model, steps_per_execution)
   1110         use_multiprocessing=use_multiprocessing,
   1111         distribution_strategy=ds_context.get_strategy(),
-> 1112         model=model)
   1113 
   1114     strategy = ds_context.get_strategy()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, shuffle, workers, use_multiprocessing, max_queue_size, model, **kwargs)
    907         max_queue_size=max_queue_size,
    908         model=model,
--> 909         **kwargs)
    910 
    911   @staticmethod

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, workers, use_multiprocessing, max_queue_size, model, **kwargs)
    777     # Since we have to know the dtype of the python generator when we build the
    778     # dataset, we have to look at a batch to infer the structure.
--> 779     peek, x = self._peek_and_restore(x)
    780     peek = self._standardize_batch(peek)
    781     peek = _process_tensorlike(peek)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in _peek_and_restore(x)
    911   @staticmethod
    912   def _peek_and_restore(x):
--> 913     return x[0], x
    914 
    915   def _handle_multiprocessing(self, x, workers, use_multiprocessing,

/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/iterator.py in __getitem__(self, idx)
     63         index_array = self.index_array[self.batch_size * idx:
     64                                        self.batch_size * (idx + 1)]
---> 65         return self._get_batches_of_transformed_samples(index_array)
     66 
     67     def __len__(self):

/usr/local/lib/python3.6/dist-packages/deepcell/image_generators/tracking.py in _get_batches_of_transformed_samples(self, index_array)
    863                     # No divisions so randomly choose a different track that is
    864                     # guaranteed to have a division
**--> 865                     new_j = np.random.choice(self.tracks_with_divisions)**
    866                     j = new_j
    867                     track_id = self.track_ids[j]

mtrand.pyx in numpy.random.mtrand.RandomState.choice()

ValueError: 'a' cannot be empty unless no samples are taken

**The following text is another version of the same type of error**

 ---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-17-559681f977cc> in <module>
      6     validation_data=test_data,
      7     validation_steps=1 // batch_size,
----> 8     callbacks=train_callbacks)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1859         use_multiprocessing=use_multiprocessing,
   1860         shuffle=shuffle,
-> 1861         initial_epoch=initial_epoch)
   1862 
   1863   def evaluate_generator(self,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1098                 _r=1):
   1099               callbacks.on_train_batch_begin(step)
-> 1100               tmp_logs = self.train_function(iterator)
   1101               if data_handler.should_sync:
   1102                 context.async_wait()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    853       # In this case we have created variables on the first call, so we run the
    854       # defunned version which is guaranteed to never create variables.
--> 855       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
    856     elif self._stateful_fn is not None:
    857       # Release the lock early so that multiple threads can perform the call

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2941        filtered_flat_args) = self._maybe_define_function(args, kwargs)
   2942     return graph_function._call_flat(
-> 2943         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
   2944 
   2945   @property

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1917       # No tape is watching; skip to running the function.
   1918       return self._build_call_outputs(self._inference_function.call(
-> 1919           ctx, args, cancellation_manager=cancellation_manager))
   1920     forward_backward = self._select_forward_and_backward_functions(
   1921         args,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    558               inputs=args,
    559               attrs=attrs,
--> 560               ctx=ctx)
    561         else:
    562           outputs = execute.execute_with_cancellation(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  ValueError: 'a' cannot be empty unless no samples are taken
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 807, in wrapped_generator
    for data in generator_fn():

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 933, in generator_fn
    yield x[i]

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/iterator.py", line 65, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "/usr/local/lib/python3.6/dist-packages/deepcell/image_generators/tracking.py", line 865, in _get_batches_of_transformed_samples
    new_j = np.random.choice(self.tracks_with_divisions)

  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice

ValueError: 'a' cannot be empty unless no samples are taken

	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
  (1) Invalid argument:  ValueError: 'a' cannot be empty unless no samples are taken
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 807, in wrapped_generator
    for data in generator_fn():

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 933, in generator_fn
    yield x[i]

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/iterator.py", line 65, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "/usr/local/lib/python3.6/dist-packages/deepcell/image_generators/tracking.py", line 865, in _get_batches_of_transformed_samples
    new_j = np.random.choice(self.tracks_with_divisions)

  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice

ValueError: 'a' cannot be empty unless no samples are taken

	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_8]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_19031]

Function call stack:
train_function -> train_function

**Comment by jizhouh** [comment]
Problem solved!

Firstly, I checked the output of **self.track_ids[track]**, and noticed that the cells that divided were not found, or found but did not have daughter information (which means it was treated as a non-division event).

Then I checked the function **_create_track_ids(self)**, and noticed that around **line 295** 

                if y_index.size > 0:  # if cell is present at all
                    # Only include daughters if there are enough frames in their tracks
                    if self.daughters is not None:
                        print('daughters',daughters_batch.get(cell, []))
                        daughter_ids = daughters_batch.get(cell, [])
                        if daughter_ids:
                            daughter_track_lengths = []
                            for did in daughter_ids:
                                # Screen daughter tracks to make sure they are long enough
                                # Length currently set to 0
                                axis = (self.row_axis - 1, self.col_axis - 1)
                                d_true = np.sum(y_batch == did, axis=axis)
                                d_track_length = len(np.where(d_true > 0)[0])
                                daughter_track_lengths.append(d_track_length > 3)
                            keep_daughters = all(daughter_track_lengths)
                            daughters = daughter_ids if keep_daughters else []
                        else:
                            daughters = []
                    else:
                        daughters = []

In my case, the data set has three division events, which are cell 12, 13, 16, where cell 13's daughters only live for 3 frames, the other two cells' daughters live for 7 frames and 9 frames (the total frame is 10)

Cell 13 was the one found but did not have daughter information, and Cell 12 and 16 were the two completely not found. Therefore, I changed the code to 

**if y_index.size > 0:
...
daughter_track_lengths.append(d_track_length > 0)**

My purpose for using this poor set was to get a basic model, and then use the model to track the rest of images to get a relatively acceptable result, so that I could save the time on manually editing the label of each cell. Those errors were just an coincident that all of my division event right fell on the edge case.
