### ISSUE TITLE
weird training error after successfully training one epoch

### ISSUE THREAD

**Issue by JunMa11** [vanvalenlab/deepcell-tf#583]
Dear DeepCell,

I encountered the following error after successfully training one epoch.

Have you encountered similar problems? Any comments would be highly appreciated.

```
train_callbacks = get_callbacks(
    model_path,
    lr_sched=lr_sched,
    tensorboard_log_dir=LOG_DIR,
    save_weights_only=num_gpus >= 2,
    monitor='val_loss',
    verbose=1)

# line 148
loss_history = model.fit_generator(
    train_data,
    steps_per_epoch=train_data.y.shape[0] // batch_size,
    epochs=n_epoch,
    validation_data=val_data,
    validation_steps=val_data.y.shape[0] // batch_size,
    callbacks=train_callbacks)
```

```
022-02-10 17:47:58.525692: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2022-02-10 17:47:58.529424: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2100000000 Hz
Epoch 1/200
   1/1854 [..............................] - ETA: 5:19:25 - loss: 0.2943 - semantic_0_loss: 0.2810 - semantic_1_loss: 0.01332022-02-10 17:48:09.261759: I tensorflow/core/profiler/lib/profiler_session.cc:126] Profiler session initializing.
2022-02-10 17:48:09.261967: I tensorflow/core/profiler/lib/profiler_session.cc:141] Profiler session started.
2022-02-10 17:48:09.262075: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1661] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
   2/1854 [..............................] - ETA: 37:38 - loss: 0.2226 - semantic_0_loss: 0.2093 - semantic_1_loss: 0.0133  2022-02-10 17:48:10.152597: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at summary_kernels.cc:106 : Resource exhausted: log/meta_nuc/train/events.out.tfevents.1644544078.cdr2592.int.cedar.computecanada.ca.115574.3990.v2; Disk quota exceeded
	Failed to flush 1 events to ./log/meta_nuc/train/events.out.tfevents.1644544078.cdr2592.int.cedar.computecanada.ca.115574.3990.v2
	Could not flush events file.
Traceback (most recent call last):
  File "deepcell_train_nuc.py", line 148, in <module>
    loss_history = model.fit_generator(
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1938, in fit_generator
    return self.fit(
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1183, in fit
    callbacks.on_train_batch_end(end_step, logs)
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 457, in on_train_batch_end
    self._call_batch_hook(ModeKeys.TRAIN, 'end', batch, logs=logs)
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 317, in _call_batch_hook
    self._call_batch_end_hook(mode, batch, logs)
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 337, in _call_batch_end_hook
    self._call_batch_hook_helper(hook_name, batch, logs)
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 375, in _call_batch_hook_helper
    hook(batch, logs)
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 2426, in on_train_batch_end
    self._stop_trace()
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 2456, in _stop_trace
    summary_ops_v2.trace_export(name='batch_%d' % batch, step=batch)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 361, in as_default
    self.flush()
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 380, in flush
    return _flush_fn(writer=self)
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 1074, in flush
    return gen_summary_ops.flush_summary_writer(resource, name=name)
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/ops/gen_summary_ops.py", line 198, in flush_summary_writer
    _ops.raise_from_not_ok_status(e, name)
  File "/home/jma/codes/deepcell/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: log/meta_nuc/train/events.out.tfevents.1644544078.cdr2592.int.cedar.computecanada.ca.115574.3990.v2; Disk quota exceeded
	Failed to flush 1 events to ./log/meta_nuc/train/events.out.tfevents.1644544078.cdr2592.int.cedar.computecanada.ca.115574.3990.v2
	Could not flush events file. [Op:FlushSummaryWriter]
2022-02-10 17:48:10.566776: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
```

**Comment by msschwartz21** [comment]
Hi Jun,

Can you tell us a bit more about your compute environment, e.g. operating system, python version, gpu, etc?

**Comment by JunMa11** [comment]
Hi @msschwartz21 ,

I'm using a cluster: https://docs.computecanada.ca/wiki/Cedar.

- python 3.8
- tensorflow 2.5.1
- cuda 11.0
- GPU: NVIDIA V100 32G
- system: Linux version 3.10.0-1160.36.2.el7.x86_64 (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) )


Following are the complete packages.

``` python
absl-py                 0.15.0+computecanada             
argon2-cffi             21.3.0+computecanada             
argon2-cffi-bindings    21.2.0+computecanada             
asttokens               2.0.5+computecanada              
astunparse              1.6.3+computecanada              
attrs                   21.4.0+computecanada             
backcall                0.2.0+computecanada              
black                   22.1.0+computecanada             
bleach                  4.1.0+computecanada              
cachetools              5.0.0                            
certifi                 2021.10.8+computecanada          
cffi                    1.15.0+computecanada             
charset-normalizer      2.0.11+computecanada             
click                   8.0.3+computecanada              
cycler                  0.11.0                           
cython                  0.29.27+computecanada            
debugpy                 1.5.1+computecanada              
decorator               5.1.1+computecanada              
DeepCell                0.11.0                           
DeepCell-Toolbox        0.10.3                           
DeepCell-Tracking       0.5.5                            
defusedxml              0.7.1+computecanada              
entrypoints             0.4+computecanada                
executing               0.8.2+computecanada              
flatbuffers             1.12+computecanada               
fonttools               4.29.1                           
gast                    0.4.0+computecanada              
google-auth             2.6.0                            
google-auth-oauthlib    0.4.6+computecanada              
google-pasta            0.2.0+computecanada              
grpcio                  1.34.1                           
h5py                    3.1.0+computecanada              
idna                    3.3+computecanada                
imageio                 2.15.0                           
importlib-metadata      4.10.1+computecanada             
importlib-resources     5.4.0+computecanada              
ipykernel               6.9.0+computecanada              
ipython                 8.0.1+computecanada              
ipython-genutils        0.2.0+computecanada              
ipywidgets              7.6.5+computecanada              
jedi                    0.18.1+computecanada             
jinja2                  3.0.3+computecanada              
joblib                  1.1.0                            
jsonschema              4.4.0+computecanada              
jupyter                 1.0.0+computecanada              
jupyter-client          7.1.2+computecanada              
jupyter-console         6.4.0+computecanada              
jupyter-core            4.9.1+computecanada              
jupyterlab-pygments     0.1.2+computecanada              
jupyterlab-widgets      1.0.2+computecanada              
keras-nightly           2.5.0.dev2021032900+computecanada
Keras-Preprocessing     1.1.2+computecanada              
kiwisolver              1.3.2                            
lxml                    4.7.1+computecanada              
markdown                3.3.6+computecanada              
markupsafe              2.0.1+computecanada              
matplotlib              3.5.1                            
matplotlib-inline       0.1.3+computecanada              
mistune                 0.8.4+computecanada              
mypy-extensions         0.4.3+computecanada              
nbclient                0.5.10+computecanada             
nbconvert               6.4.2+computecanada              
nbformat                5.1.3+computecanada              
nest-asyncio            1.5.4+computecanada              
networkx                2.6.3+computecanada              
notebook                6.4.8+computecanada              
numpy                   1.19.5                           
oauthlib                3.2.0                            
opencv-python-headless  4.5.3.56+computecanada           
opt-einsum              3.3.0+computecanada              
packaging               21.3                             
pandas                  1.4.0                            
pandocfilters           1.5.0+computecanada              
parso                   0.8.3+computecanada              
pathspec                0.9.0+computecanada              
pexpect                 4.8.0+computecanada              
pickleshare             0.7.5+computecanada              
pillow                  9.0.1+computecanada              
pip                     20.0.2                           
platformdirs            2.5.0+computecanada              
prometheus-client       0.13.1+computecanada             
prompt-toolkit          3.0.27+computecanada             
protobuf                3.19.4                           
ptyprocess              0.7.0+computecanada              
pure-eval               0.2.2+computecanada              
pyasn1                  0.4.8+computecanada              
pyasn1-modules          0.2.8+computecanada              
pycparser               2.21+computecanada               
pydot                   1.4.2+computecanada              
pygments                2.11.2+computecanada             
pyparsing               3.0.7                            
pyrsistent              0.18.1+computecanada             
python-dateutil         2.8.2                            
pytz                    2021.3                           
PyWavelets              1.2.0                            
pyzmq                   22.3.0+computecanada             
qtconsole               5.2.2                            
QtPy                    2.0.1                            
requests                2.27.1+computecanada             
requests-oauthlib       1.3.1                            
rsa                     4.8+computecanada                
scikit-image            0.18.1+computecanada             
scikit-learn            1.0.2                            
scipy                   1.5.2                            
send2trash              1.8.0+computecanada              
setuptools              46.1.3                           
six                     1.15.0+computecanada             
sklearn                 0.0                              
spektral                1.0.8                            
stack-data              0.1.4+computecanada              
tensorboard             2.8.0                            
tensorboard-data-server 0.6.1+computecanada              
tensorboard-plugin-wit  1.8.1                            
tensorflow              2.5.1                            
tensorflow-addons       0.13.0+computecanada             
tensorflow-estimator    2.5.0+computecanada              
termcolor               1.1.0+computecanada              
terminado               0.13.1+computecanada             
testpath                0.5.0+computecanada              
threadpoolctl           3.1.0                            
tifffile                2022.2.9                         
tomli                   2.0.1+computecanada              
tornado                 6.1+computecanada                
tqdm                    4.62.3+computecanada             
traitlets               5.1.1+computecanada              
typeguard               2.13.3                           
typing-extensions       3.7.4.3+computecanada            
urllib3                 1.26.8+computecanada             
wcwidth                 0.2.5+computecanada              
webencodings            0.5.1+computecanada              
werkzeug                2.0.3+computecanada              
wheel                   0.37.1                           
widgetsnbextension      3.5.2+computecanada              
wrapt                   1.12.1+computecanada             
zipp                    3.7.0+computecanada        
```

**Comment by msschwartz21** [comment]
Thanks for the additional info. This isn't an issue we've seen before but after googling the error my impression is that it may be a problem with the tensorboand call back. Have you tried removing the tensorboard log dir from the callbacks?

**Comment by JunMa11** [comment]
Yes, it works:)
Thanks for your help.
