### ISSUE TITLE
Missing loss functions when trying to train Mesmer

### ISSUE THREAD

**Issue by jgu13** [vanvalenlab/deepcell-tf#668]
**Describe the bug**
Hello,
I am trying to train Mesmer with new images and masks I annotated. I am trying to train the model by modifying [Nuclear Segmentation - DeepWatershed.ipynb](https://github.com/vanvalenlab/deepcell-tf/blob/56f2cce7e51655c188acb213e25e1c3ef0fdbef5/notebooks/training/panopticnets/Nuclear%20Segmentation%20-%20DeepWatershed.ipynb). I encountered the following warning

```
WARNING:tensorflow:Gradients do not exist for variables ['conv_0_semantic_upsample_3/kernel:0', 'conv_0_semantic_upsample_3/bias:0', 'conv_1_semantic_upsample_3/kernel:0', 'conv_1_semantic_upsample_3/bias:0', 'conv_2_semantic_upsample_3/kernel:0', 'conv_2_semantic_upsample_3/bias:0', 'conv_0_semantic_3/kernel:0', 'conv_0_semantic_3/bias:0', 'batch_normalization_0_semantic_3/gamma:0', 'batch_normalization_0_semantic_3/beta:0', 'conv_1_semantic_3/kernel:0', 'conv_1_semantic_3/bias:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss`argument?
```

and a ValueError

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[path\to\scripts\generate_segmentation.ipynb](file:///path/to/scripts/generate_segmentation.ipynb) Cell 32 in ()
     [16] # Compile the model
     [17] model.compile(loss=loss, optimizer=optimizer)
---> [18] loss_history = model.fit(
     [19]     train_gen,
     [20]     steps_per_epoch=train_gen.y.shape[0] // batch_size,
     [21]     epochs=n_epoch,
     [22]     validation_data=val_gen,
     [23]     validation_steps=val_gen.y.shape[0] // batch_size,
     [24]     callbacks=train_callbacks)

File [path\to\user\miniconda3\envs\deepcell-tf\lib\site-packages\keras\utils\traceback_utils.py:67](file:///path/to/user/miniconda3/envs/deepcell-tf/lib/site-packages/keras/utils/traceback_utils.py:67), in filter_traceback..error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File [path\to\user\miniconda3\envs\deepcell-tf\lib\site-packages\tensorflow\python\framework\func_graph.py:1147](file:///path/to/user/miniconda3/envs/deepcell-tf/lib/site-packages/tensorflow/python/framework/func_graph.py:1147), in func_graph_from_py_func..autograph_handler(*args, **kwargs)
   1145 except Exception as e:  # pylint:disable=broad-except
   1146   if hasattr(e, "ag_error_metadata"):
-> 1147     raise e.ag_error_metadata.to_exception(e)
   1148   else:
   1149     raise

ValueError: in user code:

    File "[path\to\user\miniconda3\envs\deepcell-tf\lib\site-packages\keras\engine\training.py](file:///path/to/user/miniconda3/envs/deepcell-tf/lib/site-packages/keras/engine/training.py)", line 1021, in train_function  *
        return step_function(self, iterator)
    File "[path\to\user\miniconda3\envs\deepcell-tf\lib\site-packages\keras\engine\training.py](file:///path/to/user/miniconda3/envs/deepcell-tf/lib/site-packages/keras/engine/training.py)", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "[path\to\user\miniconda3\envs\deepcell-tf\lib\site-packages\keras\engine\training.py](file:///path/to/user/miniconda3/envs/deepcell-tf/lib/site-packages/keras/engine/training.py)", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "[path\to\user\miniconda3\envs\deepcell-tf\lib\site-packages\keras\engine\training.py](file:///path/to/user/miniconda3/envs/deepcell-tf/lib/site-packages/keras/engine/training.py)", line 864, in train_step
        return self.compute_metrics(x, y, y_pred, sample_weight)
    File "[path\to\user\miniconda3\envs\deepcell-tf\lib\site-packages\keras\engine\training.py](file:///path/to/user/miniconda3/envs/deepcell-tf/lib/site-packages/keras/engine/training.py)", line 957, in compute_metrics
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    File "[path\to\user\miniconda3\envs\deepcell-tf\lib\site-packages\keras\engine\compile_utils.py](file:///path/to/user/miniconda3/envs/deepcell-tf/lib/site-packages/keras/engine/compile_utils.py)", line 438, in update_state
        self.build(y_pred, y_true)
    File "[path\to\user\miniconda3\envs\deepcell-tf\lib\site-packages\keras\engine\compile_utils.py](file:///path/to/user/miniconda3/envs/deepcell-tf/lib/site-packages/keras/engine/compile_utils.py)", line 358, in build
        self._metrics = tf.__internal__.nest.map_structure_up_to(y_pred, self._get_metric_objects,

    ValueError: The two structures don't have the same sequence length. Input structure has length 3, while shallow structure has length 4.
```

**To Reproduce**
Here is a minimum example to reproduce:
```
from deepcell.image_generators import SemanticDataGenerator
from deepcell.applications import Mesmer
from deepcell.utils.train_utils import rate_scheduler, get_callbacks, count_gpus
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import MSE
from deepcell import losses
import os
import time
import numpy as np

app = Mesmer()
X_train = np.random.rand(*(1,256,256,2))
y_train = np.random.rand(*(1,256,256,1))
X_val = np.random.rand(*(1,256,256,2))
y_val = np.random.rand(*(1,256,256,1))

model = app.model
classes = {'inner_distance': 0, 
           'outer_distance': 1, 
           'fgbg': 2}
transforms_kwargs = {'outer-distance': {'erosion_width': 0}}
seed = 42
lr_sched = rate_scheduler(lr=0.01, decay=0.99)
batch_size = 1
n_epoch = 1  # Number of training epochs
optimizer = Adam(learning_rate=0.0001, decay=0.001, clipnorm=0.01)

datagen = SemanticDataGenerator(
            rotation_range=180,
            shear_range=0,
            zoom_range=(0.75, 1.25),
            horizontal_flip=True,
            vertical_flip=True,
            )
train_gen = datagen.flow(
            {'X': X_train, 'y': y_train},
            seed=seed,
            transforms=list(classes.keys()),
            transforms_kwargs=transforms_kwargs,
            min_objects=0,
            batch_size=batch_size
            )
# Create validation generator
datagen_val = SemanticDataGenerator(
            rotation_range=0,
            shear_range=0,
            zoom_range=(0, 0),
            horizontal_flip=False,
            vertical_flip=False,
            )
val_gen = datagen_val.flow(
            {'X':X_val, 'y': y_val},
            seed=seed,
            transforms=list(classes.keys()),
            transforms_kwargs=transforms_kwargs,
            min_objects=0,
            batch_size=batch_size
            )

# Create a dictionary of losses for each semantic head
def semantic_loss(n_classes):
    def _semantic_loss(y_true, y_pred):
        if n_classes > 1:
            return 0.01 * losses.weighted_categorical_crossentropy(
                y_true, y_pred, n_classes=n_classes)
        return MSE(y_true, y_pred)
    return _semantic_loss


loss = {}

# Give losses for all of the semantic heads
for layer in model.layers:
    if layer.name.startswith('semantic_'):
        n_classes = layer.output_shape[-1]
        loss[layer.name] = semantic_loss(n_classes) # each layer has an independent loss 

# Compile the model
model.compile(loss=loss, optimizer=optimizer)
loss_history = model.fit(
    train_gen,
    steps_per_epoch=train_gen.y.shape[0] // batch_size,
    epochs=n_epoch,
    validation_data=val_gen,
    validation_steps=val_gen.y.shape[0] // batch_size)
```

**Questions:**
1. How to train Mesmer model on new images and masks?
2. How to correctly supply loss functions to the layers mentioned above?

Thank you in advance!

**Comment by msschwartz21** [comment]
Hi Claris,

Can you try working off this notebook for training Mesmer and see if that resolves your issue?
