### ISSUE TITLE
Mesmer `panopticnet` `ValueError` segmentation error on region with unusual dimensions

### ISSUE THREAD

**Issue by matt-sd-watson** [vanvalenlab/deepcell-tf#735]
**Describe the bug**
The following error appears when I try to segment a 1000x99 IMC region using the [steinbock pipeline](https://github.com/BodenmillerGroup/steinbock):

```
Traceback (most recent call last):
  File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/steinbock/segmentation/deepcell.py", line 134, in try_segment_objects
    mask = predict(img, **predict_kwargs)
  File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/steinbock/segmentation/deepcell.py", line 54, in predict
    mask = app.predict(
  File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/deepcell/applications/mesmer.py", line 306, in predict
    return self._predict_segmentation(image,
  File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/deepcell/applications/application.py", line 442, in _predict_segmentation
    output_images = self._run_model(
  File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/deepcell/applications/application.py", line 381, in _run_model
    output_tiles = self._batch_predict(tiles=tiles, batch_size=batch_size)
  File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/deepcell/applications/application.py", line 338, in _batch_predict
    batch_outputs = self.model.predict(batch_inputs, batch_size=batch_size)
  File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1147, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)

ValueError: in user code:

    File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/keras/engine/training.py", line 1801, in predict_function  *
        return step_function(self, iterator)
    File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/keras/engine/training.py", line 1790, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/keras/engine/training.py", line 1783, in run_step  **
        outputs = model.predict_step(data)
    File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/keras/engine/training.py", line 1751, in predict_step
        return self(x, training=False)
    File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/home/admin/anaconda3/envs/steinbock-snakemake/lib/python3.9/site-packages/keras/engine/input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "panopticnet" is incompatible with the layer: expected shape=(None, 256, 256, 2), found shape=(1, 256, 3744, 2)
```

**To Reproduce**

1. Attempt to segment a  1000x99 IMC region

**Expected behavior**

Segmentation should be able to proceed as usual, guven that there is nuclear/DNA signal in the ROI

**Screenshots**

Image of the DNA/Iridium IMC stain:

![Screenshot from 2024-11-27 14-58-22](https://github.com/user-attachments/assets/40f098ff-7b34-4047-9a98-19377290e95b)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Ubuntu]: Ubuntu
 - Version [e.g. 22]: 24.04
 - Python Version [e.g. 3.6.7]: 3.9.20

**Additional context**

Python package versions:

```
DeepCell==0.12.5
DeepCell_Toolbox==0.12.1
DeepCell_Tracking==0.6.4
```

**Comment by rossbar** [comment]
This should be fixed in #673 - try upgrading to deepcell-tf >= 0.12.6
